[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold", # Link using mold
    "-Zshare-generics=y"            # (Nightly) Make the current crate share its generic instantiations
]
